// The evidence boundary: measured anatomy, declared dynamics and missing biology. Numbers come from the receipts named beside them.
export const DISCLAIMERS = {
  title: "Disclaimers: what is measured, what is declared, what is missing",
  intro: "This site demonstrates how measured anatomical wiring can become a running Cadence rate patch net. The anatomical graph retains the source's connection partners and synapse counts. The runnable model also needs declared signs, gains, neuron dynamics, stimuli and body mappings. The fish duplicates a reconstructed half-brainstem, and the match page uses labelled shuffled controls. The receipts test selected circuit properties, not complete animal behavior or exact spiking equivalence.",
  sections: [
    { id: "rule", title: "1. Measured wiring, declared dynamics", paragraphs: [
      "Within each imported anatomical graph, a cell becomes a patch and a listed connection becomes a relation carrying the recorded synapse count. The compiler reads the release's tables; receipts bind the source tables and compiled net with SHA-256 digests. Missing anatomical partners are not filled in from proximity or cell type. The fish's second half is a declared duplicate of the measured half, not an additional anatomical reconstruction.",
      "A contact count is not a measured physiological weight. Here a weight combines the recorded count with a declared sign and gain; the full fish model also attenuates the body module, and the larva display lowers the protocol-selected gain. Transmitter annotations inform signs where available. The neuron response curve, time scale, sensory input and body response are declared too. The circuit protocols select gain using one training fact with the same rule for measured and shuffled wiring.",
    ] },
    { id: "larva", title: "2. The larva", paragraphs: [
      "Source: the whole-body connectome of the three-day-old Platynereis dumerilii larva (Verasztó et al. 2025, eLife 13:RP97964), read from the Jékely laboratory's public CATMAID database, project 11. The imported tables contain 25,609 cells, of which 2,664 are neurons (1,018 sensory, 1,393 interneurons, 253 motor) and 933 are effector cells (muscles, ciliated cells, glands); 32,202 synapses in 18,970 connections; 294 cell types from the paper's Supplementary file 1. 18,897 of the 25,609 cells carry no synapse in the data: 18,100 of the 22,012 cells with no neuronal or effector role (epithelium, glia, pigment cells, untyped cells) and 797 typed cells, 367 sensory neurons, 120 interneurons, one motor neuron and 309 effector cells, that the tracing left without a synapse. These cells have no synaptic route to the rest of the imported graph; their modeled state can still be changed by an explicitly applied sensory drive.",
      "Declared: the sign rule. The paper's table names a transmitter for about a quarter of the types, mostly peptidergic, and no GABAergic or glycinergic one, so every cell is compiled as excitatory. The control reading, every type without a named classical transmitter at weight zero, exists in the adapter and is not what the page runs. Under this rule the pressure response the paper's authors described (Bezares-Calderón et al. 2024, upward swimming) does not emerge; the compiled ciliary photoreceptor pathway answers with the ciliary arrest, so the page feeds the lamp's ultraviolet into those cells and not the depth.",
      "Declared: the body. What a ciliated cell's activity does (its beat drives the larva forward and turns it when the two sides differ), what the cholinergic ciliomotor neuron MC does (arrest, after Verasztó et al. 2017), what the serotonergic Ser-h1 and Loop neurons do (raise the beat), what the longitudinal and parapodial muscles do (bend the body, raise the parapodia), the helix, the sinking, the walls of the tank. The constants are in larva_dictionary.js and larva_body.js. Declared: the senses, how a lamp's light reaches each eye and eyespot through its pigment cup, how a tap reaches the collar receptor neurons and how long their response outlasts the pulse. Declared: the time scale, one brain step for 40 milliseconds of the larva's time, a fifth of the unit's time constant.",
      "Declared: the demo gain. The protocol selected a gain of 0.2531 on the training fact, 0.975 of the critical gain of the unit, where the net's slowest mode makes a startle last thirteen seconds. The page runs the net at 0.8 of the selected gain, 0.78 of critical, where a startle releases in two seconds, matching the intended display time scale. This display adjustment is separate from the scored protocol result. The selected gain stays the control, and the scan is in the table below.",
      "Circuit checks: five of five scored predicates not used to select gain, derived from the papers that mapped the eye, startle and ciliary photoreceptor circuits pass on the measured wiring; six shuffled wirings pass 2, 0, 0, 1, 1 and 0 (data/receipt_platynereis.json). Version 1 of that protocol, which read two of its rows differently and failed them on every wiring, ships beside it as data/receipt_platynereis_v1.json.",
    ] },
    { id: "fish", title: "3. The fish", paragraphs: [
      "Source: one side of the hindbrain of a larval zebrafish, 2,884 neurons and 75,195 synapses (Vishwanathan et al. 2024, Nature Neuroscience 27:2340), with 609 cells classified by the authors; the facts run on their own model scope of 343 cells. The whole-fish release counts 187,052 cell bodies; this is one region of one side. Measured: connection partners and counts. Declared: the authors' model sign rule, Ve2 vestibular neurons inhibitory and every other neuron excitatory.",
      "Declared: the second half of the brainstem is a mirror copy of the reconstructed half, and the inhibition between the halves is absent from the data. The saccadic burst that starts an eye movement comes from neurons outside the reconstructed region, so the page declares it, and the eye's jump during the burst is a declared pulse while the hold afterwards is the compiled net's. The body module's cells (251) carry no sign in the data; compiled as excitatory, their loop ignites the net at the integrator's gain, so the page lowers that module's gain by the smallest amount on a declared grid that keeps the net from igniting. The swim bouts, the hunt and the escape are a labelled pilot. The eye muscles' geometry, the time scale and the vestibular mapping are declared.",
      "Circuit checks: five of five scored rows not used to select gain on the measured wiring, against approximately strength-matched rewires at four and degree-only rewires at three (data/receipt_oculomotor.json, version 1 beside it as data/receipt_oculomotor_v1.json); the hold after a saccade lives in the recurrence among the interneurons: with that recurrence cut no gain passes the training fact and every row fails, without the motor feedback every row still passes, and the same wiring read feed-forward answers nothing one step after the burst (data/coupling_arms.json).",
    ] },
    { id: "wholefish", title: "4. The whole fish, and why it is not here", paragraphs: [
      "The whole-fish release inspected for this demo, Fish1 (Petkova et al. 2025, Lichtman and Engert laboratories with Google Connectomics), is an automated segmentation of a seven-day-old larva, 187,052 cell bodies and about thirty million synapses, that its authors opened for community proofreading. We measured it rather than describe it. In a random sample of 102,419 of its axon-to-dendrite synapses, 1.8 percent of the sending segments carry a cell body, 32.7 percent of the receiving segments do, and 0.78 percent of the synapses join two cells that both have one. Taking every synapse onto 4,941 cells with a cell body, 4.4 percent come from a segment with a cell body. Of the 47,288 segments that have received a proofreading edit, 2,709 are cells with a cell body; forty of them, sampled, receive a median of 162 synapses, consistent with more complete dendrites, and send a median of 15, consistent with fragmented axons, and 2.9 percent of what they receive comes from another proofread cell. A graph of that fish restricted to its proofread cells would keep about three of every hundred of their inputs.",
      "We did not join fragments to cell bodies by proximity or by any rule, because that would be inventing connections. The compiler has a Fish1 adapter and the two probes; their receipts ship here as data/fish1_fragmentation.json and data/fish1_probe.json. The retained sample explains why this release was not used as a complete cell-to-cell graph here; it does not assess later proofreading updates.",
    ] },
    { id: "model", title: "5. The model", paragraphs: [
      "The browser implements the Cadence rate neuron and settling step used by the exported payload: each patch holds a potential and reads out an activity. The declared graded setting is threshold 0, slope 0.25. The library setting used as a control in these experiments, slope 4 and threshold 1.5, did not recover graded persistence on the fish wiring. The displayed circuit models use fixed weights and declared sensory and motor dictionaries; they do not demonstrate learning.",
      "This rate model omits electrical coupling, neuromodulators and neuropeptides acting at a distance, and individual spike timing. Its fixed-point equation follows exactly from its update rule. Applying that equation to a spiking model additionally requires a justified stationary-rate reduction and matching transfer law. The recorded LIF experiment gives pattern similarity, cosine 0.965 under sustained drive over 88 undriven cells, including silent cells; its tested parameter scan did not recover the rate model's graded persistence. Neither observation proves exact spiking equivalence or that the omitted biology is unnecessary.",
    ] },
    { id: "protocol", title: "6. How the facts were scored", paragraphs: [
      "Each animal has a protocol file in the compiler with its facts, sources, predicates and freeze history; the receipt carries them, and the match page shows every predicate. One fact selects the gain by scanning from the least excitable gain upward and stopping at the first ignition; the remaining rows are evaluated at the selected gain. Each shuffled wiring selects its own gain by the same rule. The protocols record exploratory measured runs and some null comparisons before freezing, plus revisions after earlier failures. The five other scored checks are therefore separate from gain selection, not blind validation. Earlier receipts and the stated exploratory history remain available.",
      "Protocol receipts identify their source tables, compiled net, protocol digest and package version; they are records of the reported runs. The compiler itself is not published. What it produces, the compiled nets and every receipt, ships with this site in its data folder, and the data behind them are the authors' public releases. This site runs from static files.",
    ] },
  ],
  receipts: { title: "The receipts behind this page", items: [
    ["./data/larva_census.json", "the larva census"], ["./data/larva_gain_scan.json", "the larva gain scan"], ["./data/receipt_platynereis.json", "the larva facts"],
    ["./data/receipt_oculomotor.json", "the fish facts"], ["./data/fish1_fragmentation.json", "Fish1 fragmentation"], ["./data/fish1_probe.json", "Fish1 proofread probe"],
    ["./data/coupling_arms.json", "the fish coupling arms"], ["./data/receipt_platynereis_v1.json", "larva facts, version 1"], ["./data/receipt_oculomotor_v1.json", "fish facts, version 1"],
    ["./match.html", "every predicate, result and exploratory disclosure"],
  ] },
};
