// Explanatory claims stay separate from the receipt values rendered by explain_page.js.
export const EXPLAIN = {
  title: "From an animal's wiring to local agreement",
  intro: "An animal connectome can supply the wiring of a Cadence patch net: one patch per represented cell, with local relations carrying the measured synapse counts. The compiler adds an explicit neuron model and sensory and motor interfaces. This demo shows that construction running, then asks which circuit functions it preserves. The mathematical bridge is exact for a specified rate model; its reduction from spikes requires additional assumptions and evidence.",
  sections: [
    { id: "copy", title: "1. Compile the measured anatomy", paragraphs: [
      "Start with two tables: cells and synapses. Preserve the cell identities and the direction and contact count of each included connection. A patch holds a potential u; its activity r is read through a declared response curve φ. A connection from cell j to cell i contributes Wᵢⱼrⱼ to the receiving patch's input. Recurrence stays in the graph.",
      "Counts are anatomical measurements; effective weights are model choices built from them. Here Wᵢⱼ is gain × contact count × sender sign × sender attenuation. Signs, response curve, time step, external drive and body mechanics are declared. The fish's full hindbrain model also attenuates the axial module. The construction uses no trained hidden layer or learned output decoder.",
      "The fish reconstruction contains 2,884 neurons and 75,195 synapses from one side of a larval hindbrain (Vishwanathan et al. 2024). The circuit comparison below uses its 343-neuron oculomotor subset: 255 integrator neurons, 34 vestibular neurons and 54 abducens neurons. It is a circuit model, with a separately declared swimming pilot.",
    ] },
    { id: "paste", title: "2. Repair the local equations", paragraphs: [
      "Each patch sums its incoming activities and moves its potential a fraction of the way toward that input. All patches participate in the same recurrent system. With sensory drive held fixed, a fixed point is a state where every local equation agrees. The equations below are the ones the browser engine implements.",
      "This identity does not guarantee convergence. A contraction is a sufficient condition for a unique reachable fixed point; the measured directed wiring near the selected gain has no such certificate here. A small equation residual measures agreement with the model, not correctness about the animal. The gaze-holding experiment also measures a slowly decaying state after a burst, not an exactly stationary memory.",
    ] },
    { id: "spiking", title: "3. The precise bridge from spikes to patches", paragraphs: [
      "In words: a spiking neuron integrates the current its synapses deliver, fires when its potential crosses a threshold, and resets. Over any window longer than a few spikes, what it passes on is a rate, a saturating function of its input. A network of them under a steady input stops changing once every neuron fires at the rate its input dictates and every input is the sum of the rates it receives, weighted by the synapses. That condition is the fixed point below, and a patch net is built from it: each patch repairs its potential toward what its synapses deliver, the membrane with the spikes averaged out, and rests exactly where the condition holds. On the brainstem wiring the two agree neuron by neuron, cosine 0.965 and rank correlation 0.97 over the 88 undriven cells, and both ignite into the same pattern, cosine 0.94.",
      "A spiking model can share these fixed-point equations if its stationary firing rates admit a closed response law r = φ(Wr + d), in matched units and under the chosen input conditions. A patch net with that same W, d and φ then represents the same stationary rate solutions. To obtain the same output in practice, both models must reach corresponding solutions and use the same readout. This is the conditional sense in which rate function can be preserved in principle.",
      "Agreement and Surprise derives an exact charge-balance identity for a specified integrate-and-fire model, including the reset term. That identity constrains average inputs, potentials and firing rates. It does not close a rate law, prove stationarity, or identify the demo's rectified sigmoid with the spiking model's response curve. In general, the average of φ(u) differs from φ of the average u.",
      "The demo's two engines share anatomical counts and sign conventions, but choose their weights, input units and neuron laws separately. Their rate-pattern comparison is empirical evidence for this abstraction in a tested regime. It does not prove equivalence of spike times, transients, oscillations, learning or animal behavior. The live comparison lets those differences be inspected.",
    ] },
    { id: "match", title: "4. What the wiring preserves in these tests", paragraphs: [
      "The zebrafish protocol selects gain using one persistence check, then scores five other checks: graded retention, two slow modes, a vestibular push, concentration of eye-position sensitivity and abducens recruitment. A structural projection row is displayed but not counted. The measured circuit passes five of five; degree-preserving shuffles pass three, and shuffles that also approximately match incoming strengths pass four, across six seeds each.",
      "These are circuit-level checks inspired by the paper and imaging data. They were developed after exploratory runs; some null results were also inspected before the final protocol. The receipt discloses that history. 'Held-out' in its row labels means not used for gain selection, not an untouched prospective biological validation. The full fish animation uses additional modeling choices and is outside this receipt's scope.",
    ] },
    { id: "feedforward", title: "5. Why retaining recurrence matters", paragraphs: [
      "A stateless feed-forward reading of this wiring loses its output when a burst ends. The recurrent rate model retains a decaying level. The table compares those specific implementations and makes the role of persistent state visible. It is not a comparison against every feed-forward architecture with history, or against other recurrent models.",
    ] },
    { id: "cost", title: "6. Cost is a separate measurement", paragraphs: [
      "In words: a spiking simulation must place every spike, ten thousand steps per simulated second at a tenth of a millisecond, and deliver each spike along its fan-out, so a busy net costs more than a quiet one. A settling step is one pass over the synapses at the pace of the equilibrium, twenty-five per second at the declared 200 ms constant. On the same wiring and the same machine that is 26 times cheaper on the whole hindbrain reconstruction and 110 times on the oculomotor circuit at the declared constant, 2.6 and 11 times at a biological 20 ms, and 0.24 times on the quiet larva, where almost nothing fires and the spiking model wins. Settling wins where the net is busy, which is where a brain spends its time.",
      "The rate model avoids placing individual spikes and can take coarser steps when the chosen task permits it. These engine timings use the same anatomical payloads on one machine. The ratios depend on activity, implementation and the declared time scale; they do not establish a speedup at matched functional accuracy.",
      "The spiking implementation takes 0.1 ms steps. The rate model takes 25 steps per simulated second at the demo's declared 200 ms time constant, or 250 at a 20 ms constant. The sparse, weakly driven larva is cheaper in the spiking implementation. A useful efficiency claim must retain both that result and the fidelity conditions.",
    ], costNote: "Ratios are spiking wall time at 0.35 mV divided by settling wall time; values below 1 favor spiking. The larva's 25,609 represented cells include non-neural cells. Timings are from the stored benchmark, not your browser." },
    { id: "larva", title: "7. From a circuit to a whole-body connectome", paragraphs: [
      "The landing page uses the three-day Platynereis dumerilii reconstruction (Verasztó et al. 2025): 25,609 traced cells, including 2,664 neurons and 933 effector cells. Stimuli enter identified sensory populations and activity is read from identified muscles and ciliated cells. Cells with no synaptic role remain represented; cell count is not neuron count.",
      "Its receipt reports five of five circuit checks at the selected gain, while six degree-preserving shuffled wirings score two, zero, zero, one, one and zero. The sensory routing is anatomical. Transmitter assumptions, gain, stimulus strengths, rate dynamics and how effector activity moves a body remain declared. Those circuit results and a moving animation do not establish that the simulated animal behaves like a living larva.",
      "The next evidence step is a comparison with matched sensory input and motor readout, measuring task behavior and transients across the spiking and patch models, with uncertainty across trials and suitable controls. For claims about learned or adaptive animal behavior, a uniform-random policy is also required. This demo establishes a reproducible anatomy-to-model construction and selected circuit correspondences.",
    ] },
  ],
  appendix: { title: "Inspect the construction", items: [["copy.html", "wiring ledger"], ["paste.html", "gain and persistence"], ["match.html", "scored checks and shuffles"], ["why.html", "spiking and settling, live"], ["disclaimers.html", "model declarations"]] },
};
