// Supplied decoders for neural navigation. These gains/action meanings are
// engineering candidates, not a biological calibration or a learned route.
// No decoder receives fruit coordinates, room geometry or a desired bearing.
import { GRAVITY, sin_ } from "./body.js";
import { settledMotor, SETTLED_MOTOR_GROUPS } from "./motor.js";
import { ASSISTED_PLANE_LIMIT } from "./assisted-life.js";
export const TARGET_CANDIDATES = Object.freeze([
  Object.freeze({ fruit: "banana", odour: "decaying_fruit" }),
  Object.freeze({ fruit: "bread", odour: "yeasty" }),
]);
export const POLICY_OUTPUTS = Object.freeze(["mbon:MBON11:right", "mbon:MBON05:left"]);
export const NAVIGATION_READOUTS = Object.freeze([
  "dn:DNa02:left", "dn:DNa02:right", "dn:DNp09", "dn:landing", "dn:DNp03", "mn9",
]);
export const NAVIGATION_GAINS = Object.freeze({ yaw: 6, yawLimit: 2.5, forward: 0.3, vertical: 0.12,
  hoverAdmittanceSeconds: 1, planeLimit: ASSISTED_PLANE_LIMIT });
const finite = x => typeof x === "number" && Number.isFinite(x);
const clip = (x, lo, hi) => Math.max(lo, Math.min(hi, x));

/** Attention suppresses the other odor; all other sensory inputs are unchanged. */
export function attendedSenses(senses, fruit = null) {
  if (!senses || typeof senses !== "object" || Array.isArray(senses) || !Object.values(senses).every(finite)) throw new TypeError("invalid sensory snapshot");
  if (fruit !== null && !TARGET_CANDIDATES.some(c => c.fruit === fruit)) throw new RangeError("unknown attended odor");
  const out = { ...senses };
  if (fruit !== null) for (const c of TARGET_CANDIDATES) if (c.fruit !== fruit) {
    for (const side of ["left", "right"]) out[`orn:${c.odour}:${side}`] = 0;
  }
  return out;
}

export function candidateScore(readouts) {
  if (!POLICY_OUTPUTS.every(name => finite(readouts?.[name]))) throw new TypeError("missing candidate MBON readouts");
  return readouts[POLICY_OUTPUTS[0]] - readouts[POLICY_OUTPUTS[1]];
}

export function targetProbabilities(candidates, temperature = 0.3) {
  if (!finite(temperature) || temperature <= 0 || !Array.isArray(candidates) || candidates.length !== TARGET_CANDIDATES.length
    || !candidates.every((c, i) => c?.fruit === TARGET_CANDIDATES[i].fruit && finite(c.score))) throw new TypeError("invalid target candidates");
  const scores = candidates.map(c => c.score / temperature), peak = Math.max(...scores);
  const weights = scores.map(x => Math.exp(x - peak)), total = weights.reduce((a, b) => a + b, 0);
  if (!finite(total) || total <= 0) throw new RangeError("nonfinite target distribution");
  return weights.map(w => w / total);
}

export function selectTarget(candidates, draw, temperature = 0.3) {
  if (!finite(draw) || draw < 0 || draw >= 1) throw new RangeError("invalid target draw");
  const p = targetProbabilities(candidates, temperature);
  let sum = 0;
  for (let i = 0; i < p.length; i++) { sum += p[i]; if (draw <= sum) return candidates[i].fruit; }
  return candidates.at(-1).fruit;
}

/** Population means, not raw odor differences, determine every route request.
 * Avoidance reverses forward/yaw requests in this declared action decoder.
 * Vertical DN decoding is a candidate mapping, not a claim about DNp03 biology.
 * The assistance supplies hover thrust. Its horizontal projection through the
 * neural wing-plane requests is g*(sin(betaL)+sin(betaR))/2. A declared one-
 * second admittance converts this acceleration to a velocity request. This is
 * assisted amplification, NOT the thrust generated by the weak neural power
 * readouts. Zero neural outputs give zero route request; no cruise bias is added. */
export function decodeNavigation(readouts, action = 0) {
  if (![...NAVIGATION_READOUTS, ...SETTLED_MOTOR_GROUPS].every(name => finite(readouts?.[name])) || ![0, 1].includes(action)) throw new TypeError("invalid neural navigation readouts");
  const sign = action === 0 ? 1 : -1, g = NAVIGATION_GAINS;
  const wings = settledMotor(readouts).wings;
  const betaL = clip(wings[2], -g.planeLimit, g.planeLimit), betaR = clip(wings[3], -g.planeLimit, g.planeLimit);
  const assistedForwardAcceleration = GRAVITY * (sin_(betaL) + sin_(betaR)) / 2;
  return {
    yawRate: sign * clip(g.yaw * (readouts["dn:DNa02:right"] - readouts["dn:DNa02:left"]), -g.yawLimit, g.yawLimit),
    forwardSpeed: sign * clip(g.forward * clip(readouts["dn:DNp09"], 0, 1)
      + g.hoverAdmittanceSeconds * assistedForwardAcceleration, -g.forward, g.forward),
    verticalSpeed: g.vertical * clip(readouts["dn:DNp03"] - readouts["dn:landing"], -1, 1),
    feed: clip(readouts.mn9, 0, 1),
  };
}
